# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jMYYUEnHuhGdEI83xl6JDRZkzzF4shjf
"""

from os import listdir
from os.path import isfile, join
fichiers = [f for f in listdir(monRepertoire) if isfile(join(monRepertoire, f))]