# -*- coding: utf-8 -*-
"""class_inverse_index.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tVuW_naf56QBiBxr5HdjFVZUCDeBx3-O
"""

class index_inverse :
  def __init__(self):
    self.urls = urls
  def __init__(self, docId, frequency):
    self.docId = docId
    self.frequency = frequency