# -*- coding: utf-8 -*-
"""Serveur-web.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1czl9-TsSL4slJwev8ym-4yNkOcuOOi6S
"""
""" cette fonction permet de créer notre serveur web """

import http.server
 
PORT = 80                                           # le port de notre serveur
server_address = ("", PORT)

server = http.server.HTTPServer                     # stocker l'adresse de serveur sous forme d'une variable
handler = http.server.CGIHTTPRequestHandler         # gérer les requêtes http
handler.cgi_directories = ["/"]
print("Serveur actif sur le port :", PORT)

httpd = server(server_address, handler)
httpd.serve_forever()
