# -*- coding: utf-8 -*-
"""Serveur-web.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1czl9-TsSL4slJwev8ym-4yNkOcuOOi6S
"""

import http.server
import socketserver

PORT = 80
server_address = ("", PORT)

handler = http.server.SimpleHTTPRequestHandler
httpd = socketserver.TCPServer(server_address,handler)

print("Serveur actif sur le port :", PORT)


httpd.serve_forever()