# -*- coding: utf-8 -*-
"""TF-IDF.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NUzKS0r1uqiHjcEV4zGiuq7X_OyOPB2A

Cette méthode permet de calculer TF (Term Frequency)
"""

def calculer_TF (terme, document) :
  tf ={}
  longeur_doc = len (document)
  for mot, nb in terme.items () :
    tf[mot] = nb / float (longeur_doc)

  return tf

"""Cette méthode permet de calculer IDF (Inverse Document Frequency)"""

import math
def calculer_IDF (documents) :
  n = len (documents)
  idf = dict.fromkeys(documents[0].keys (), 0)
  for document in documents :
    for mot, val in document.items ():
      if val > 0 :
        idf[mot] += 1

    for mot, val in idf.items () :
      idf[mot] = math.log (n / float (val))
  
  return idf

"""Maintenant on calcule TF_IDF"""

# idfs = calculer_IDF (documents)
def calculer_TF_IDF (document,idfs) :
  tfidf = {}
  for mot, val in document.items() :
    tfidf [mot] = val * idfs [mot]

  return tfidf