# -*- coding: utf-8 -*-
"""trier_score.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UbBtiTrXX8ezxnJTTG2yXdyf-UvUu86T
"""

def matching_score(query):
    query_weights = {}
    for key in tf_idf: 
        if key[1] in idfs:
            query_weights[key[0]] += tf_idf[key]